"""Initial migration

Revision ID: 64cb6b9b6102
Revises: 
Create Date: 2025-08-04 23:02:37.717642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64cb6b9b6102'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phonenumber', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.Column('id_varified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('edited_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email_id'), 'users', ['email_id'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('vehicle_info',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('chasie_number', sa.String(), nullable=True),
    sa.Column('engineno', sa.String(), nullable=True),
    sa.Column('yom', sa.String(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('date_of_sale', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('edited_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_index(op.f('ix_vehicle_info_vehicle_id'), 'vehicle_info', ['vehicle_id'], unique=False)
    op.create_table('service_history',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('date_service', sa.DateTime(), nullable=True),
    sa.Column('odmeter_reading', sa.Float(), nullable=True),
    sa.Column('warenty_status', sa.Boolean(), nullable=True),
    sa.Column('cost_of_service', sa.Float(), nullable=True),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('edited_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle_info.vehicle_id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_index(op.f('ix_service_history_service_id'), 'service_history', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_history_service_id'), table_name='service_history')
    op.drop_table('service_history')
    op.drop_index(op.f('ix_vehicle_info_vehicle_id'), table_name='vehicle_info')
    op.drop_table('vehicle_info')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
